//> using scala "3.3.4"
//> using platform "jvm", "scala-js", "native"
//> using jvm "8"

//> using dep "org.scalacheck::scalacheck::1.18.1"
//> using test.dep "org.scalameta::munit::1.0.0"
//> using test.dep "org.scalameta::munit-scalacheck::1.0.0"

//> using option "-Xfatal-warnings"
//> using option "-Wunused:all"
//> using test.option "-Wunused:imports"

//> using jsVersion "1.16.0"
//> using nativeVersion "0.5.5"

//> using publish.organization "io.github.martinhh"
//> using publish.name "scalacheck-derived"
//> using publish.computeVersion "git:tag"
//> using publish.description "A library providing automatic derivation of scalacheck Arbitrary instances for Scala 3."
//> using publish.url "https://github.com/martinhh/scalacheck-derived"
//> using publish.license "Apache 2.0:http://opensource.org/licenses/Apache-2.0"
//> using publish.developer "martinhh|Martin Hansen|https://martinhh.github.io/"
//> using publish.versionControl "github:martinhh/scalacheck-derived"
//> using publish.repository "central-s01"
//> using publish.gpgKey "0C040BA69968998D71130D3E6796C3A8035FF011"
